name: .NET Publish

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Build and Pack
      run: |
        dotnet build Material.Icons.Avalonia
        dotnet pack Material.Icons.Avalonia
    - name: Publish to Nuget
      run: dotnet nuget push "Material.Icons.Avalonia\bin\Debug\*.nupkg" --api-key ${{secrets.NUGET_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate
    - name: Publish to GitHub Packages
      run: dotnet nuget push "Material.Icons.Avalonia\bin\Debug\*.nupkg" --api-key ${{secrets.GITHUB_TOKEN}} --source https://nuget.pkg.github.com/AvaloniaUtils/index.json --skip-duplicate
